### ISSUE TITLE
Iceberg sink race condition creates corrupted data files

### ISSUE THREAD

**Issue by calvin681** [Netflix/mantis#129]
### Context

Explain symptoms and other details for the issue.

### Steps to reproduce

Explain the steps to reliably reproduce the issue.

### Expected behavior

Explain what you think should happen.

### Actual Behavior

Explain what actually happens instead.

**Comment by jeffchao** [comment]
@sundargates is this closed from #130 ? You should be able to verify in your staging or prod by killing the `IcebergCommiterStage` I believe.

**Comment by sundargates** [comment]
Yes, this has been addressed. let me close this issue.
