### ISSUE TITLE
Make mantis Java 17 Compatible

### ISSUE THREAD

**Issue by sundargates** [Netflix/mantis#348]
### Context

We would like to have Mantis compiled using JDK 17. However, since mantis-runtime is used in several jobs built using JDK 17, we cannot target 17-level compatibility at runtime. Thus, we would like the overall codebase to be compiled using Java 17 while still targeting JRE8-level compatibility.

**Comment by kparnami1** [comment]
Hello @sundargates,
I would like to work on this issue, could you please assign this to me? 
Also, please let me know if I can ping you on any messenger.
Thank you.

**Comment by kparnami1** [comment]
Hey @sundargates, 
I was not able to locate why gradle-8 is not supporting java-library in subprojects, could you guide me with this?
Is any chat platform available to discuss more on this?

Thanks.

**Comment by cypherean** [comment]
Hey @sundargates 
Can I take this up?
Thanks!

**Comment by sundargates** [comment]
@cypherean It looks like this is a duplicate of https://github.com/Netflix/mantis/issues/355.
