### ISSUE TITLE
Question: How to Autoscale DEFAULT ResourceClusterProvider?

### ISSUE THREAD

**Issue by crioux-stripe** [Netflix/mantis#628]
### Context
We've deployed Mantis and are able to get the master to accept work and submit it to an ASG backed DEFAULT `ResourceClusterProvider`. However the default doesn't come with autoscaling and we'd like to test our implementation of `ResourceClusterProvider` as well as have our cluster autoscale.

What request and payload do we need to submit to the master to assign an autoscaling policy to DEFAULT? The docs don't have anything here but I'd be happy to submit a pull request to them to get a section started on managing `ResourceClusterProvider`s.

**Comment by sundargates** [comment]
@Andyz26 Can you take a stab at this?

**Comment by Andyz26** [comment]
hi @crioux-stripe to enable resource cluster auto-scaling you need to add scaling rules to the target cluster id from this API: [link](https://github.com/Netflix/mantis/blob/56745b3d826e21daeaaa2c4b6a1b9ec0f73ef981/mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java#L248).

The request will look something like this:
```JSON
{
    "clusterId": {"resourceID": "{{resourceClusterId}}"},
    "rules": [
        {
            "clusterId": {
                "resourceID": "{{resourceClusterId}}"
            },
            "skuId": {
                "resourceID": "medium"
            },
            "minIdleToKeep": 10,
            "minSize": 1,
            "maxIdleToKeep": 15,
            "maxSize": 20,
            "coolDownSecs": 300
        },
        {
            "clusterId": {
                "resourceID": "{{resourceClusterId}}"
            },
            "skuId": {
                "resourceID": "large"
            },
            "minIdleToKeep": 10,
            "minSize": 1,
            "maxIdleToKeep": 15,
            "maxSize": 30,
            "coolDownSecs": 300
        }
    ]
}
```

**Comment by crioux-stripe** [comment]
Thanks @Andyz26 !
