### ISSUE TITLE
404 page for Mantis website

### ISSUE THREAD

**Issue by vganapat** [Netflix/mantis#662]
### Context

The Official Website is down

### Steps to reproduce

Navigate to https://netflix.github.io/mantis/

### Expected behavior

I should see the docs website

### Actual Behavior

I see 

<img width="1723" alt="Screenshot 2024-04-26 at 4 29 43 PM" src="https://github.com/Netflix/mantis/assets/3590095/64190531-1e86-4b86-be16-8d15b7214645">

**Comment by hmitnflx** [comment]
Thanks for reporting, the docs website should be up now.
